import pyautogui as agui
agui.hotkey('winleft', 'd')
agui.hotkey('winleft', 's')
agui.typewrite("Chrome")
agui.press("enter")
agui.sleep(3)
agui.click(350, 300)
agui.click(351, 301)
agui.sleep(3)
agui.typewrite("bestfig.xyz")
agui.press("enter")
